### ISSUE TITLE
EBS volumes for FortiGate

### ISSUE THREAD

**Issue by ratanGit** [AJLab-GH/transitgwyconnect#5]
In fgtvm.tf and fgtvm2.tf:

  ebs_block_device {
    device_name = "/dev/sdb"
    volume_size = "30"
    volume_type = "standard"
  }

In your Terraform I see the volume type set to "standard" which seems to be a previous-generation EBS volume types (magnetic)
https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volume-types.html

Is that a necessity for the FortiGate AWS? Can we use a general purpose SSD instead?

**Comment by jgrammen-agilitypr** [comment]
In fgtvm.tf and fgtvm2.tf: 
```
  root_block_device {
    volume_type = "standard"
    volume_size = "2"
  }

  ebs_block_device {
    device_name = "/dev/sdb"
    volume_size = "30"
    volume_type = "standard"
  }
  ```
you are setting the volume_type to "standard", but the ami defaults to
![image](https://github.com/user-attachments/assets/0761bdce-c2b1-4281-9293-4fb7a8ab875e)
so you are overriding the ami default gp2 disk type and instead forcing aws "standard" (https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volume-types.html#vol-type-prev ) disks.

**Comment by ajlab-gh** [comment]
@jgrammen-agilitypr  @ratanGit 

This repository was used to develop a strategy to feed the cloud-init bootstrapping via s3. The original templates did not include the functionality until PR 272. 

https://github.com/fortinet/fortigate-terraform-deploy/pull/272

I recommend creating an issue or doing a PR in the official repo!

https://github.com/fortinet/fortigate-terraform-deploy/issues

Cheers,
